### ISSUE TITLE
[功能建议]加一个记录分数的功能

### ISSUE THREAD

**Issue by ElainaFanBoy** [KimigaiiWuyi/MajsoulUID#10]
效果如图
![IMG_20240930_112052](https://github.com/user-attachments/assets/3e3aa361-9b38-4c72-8b87-198fae2f214a)

**Comment by KimigaiiWuyi** [comment]
https://github.com/KimigaiiWuyi/MajsoulUID/commit/4ce2b071456e7690b8a6c1b3a958c18706cf3ed6 已添加
