### ISSUE TITLE
支持欧美服吗

### ISSUE THREAD

**Issue by Agnes4m** [KimigaiiWuyi/MajsoulUID#3]
同标题，外服能支持查询吗

**Comment by KimigaiiWuyi** [comment]
不清楚, 来个主界面截图看看

**Comment by Agnes4m** [comment]
手机谷歌商店下的
![0d0631e0e47d821482cac6a3e67ab6af_720](https://github.com/KimigaiiWuyi/MajsoulUID/assets/70925546/0d06751e-6d2e-4747-bad7-05bd89e3b852)

**Comment by KimigaiiWuyi** [comment]
> 手机谷歌商店下的 ![0d0631e0e47d821482cac6a3e67ab6af_720](https://private-user-images.githubusercontent.com/70925546/314455204-0d06751e-6d2e-4747-bad7-05bd89e3b852.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5Mjk1OTQsIm5iZiI6MTcxMDkyOTI5NCwicGF0aCI6Ii83MDkyNTU0Ni8zMTQ0NTUyMDQtMGQwNjc1MWUtNmQyZS00NzQ3LWJhZDctMDViZDg5ZTNiODUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDEwMDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NjhlOTUyYTA3NDYyMjA5NWY4OTY2ZjE5NGMxYWE0NWQ4MDc1YjI5ZTYzYzM3MzY4MWE3YjU0ZmViNzI5OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H8uk4Tkx0qpImxvSmdyygBUp_mRjURK1_1SqxP_U54s)

最近半年有打过金之间吗
也许是可以的，我不太清楚，你的ID不太好打

**Comment by Agnes4m** [comment]
雛桃の兔子先生

**Comment by Agnes4m** [comment]
so如何了

**Comment by KimigaiiWuyi** [comment]
> so如何了

是可以的
